# Generated by Django 5.2.16 on 2026-07-15 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_api', '0004_studentprofile_profile_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('needs_review', 'Needs review'), ('verified', 'Verified'), ('error', 'Error')], default='incomplete', max_length=20)),
                ('missing_sources', models.JSONField(blank=True, default=list)),
                ('last_error', models.TextField(blank=True, default='')),
                ('engine', models.CharField(blank=True, choices=[('ai', 'AI holistic judge'), ('rule_fallback', 'Deterministic fallback')], default='', max_length=20)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_check', to='django_api.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=150)),
                ('dimension', models.CharField(max_length=50)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('severity', models.CharField(choices=[('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('expected_value', models.TextField(blank=True, default='')),
                ('found_value', models.TextField(blank=True, default='')),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolution', models.CharField(blank=True, choices=[('confirmed', 'Confirmed by student'), ('ignored', 'Ignored by student'), ('clarified', 'Clarified by student'), ('auto_cleared', 'Auto-cleared on reanalysis'), ('superseded', 'Superseded by new upload')], default='', max_length=20)),
                ('student_note', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='verification.verificationcheck')),
            ],
            options={
                'ordering': ['is_resolved', '-created_at'],
            },
        ),
    ]
