# Generated by Django 5.2.16 on 2026-07-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationitem',
            name='source_signature',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
