"""
Django settings for korgut_backend project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load ANTHROPIC_API_KEY / GITHUB_TOKEN / etc. from .env before any agent code runs.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the original dev-only value so local setups are unaffected;
# set DJANGO_SECRET_KEY in .env for any server that's reachable off localhost.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or \
    'django-insecure-0zav109$orgckjm3w+%%8v!lxt&4)qv68d^w*f%@fid@_y!c83'

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (fail closed): an unset/misconfigured DJANGO_DEBUG in a
# deploy environment must never silently open a debug server to the
# internet. Local dev sets DJANGO_DEBUG=true explicitly in .env.
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() == "true"

# Defaults to localhost only (fail closed) so a missing env var on a real
# server rejects Host headers instead of accepting anything ("*"). Any
# server reachable off localhost (staging, prod) must set
# DJANGO_ALLOWED_HOSTS explicitly -- see deployment_checklist_to_do.md.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'django_api',
    'institutes_list',
    'verification',
    'universities',
    'institutes',
    'notifications',
    'project_superuser',
    'url_discovery',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'korgut_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'korgut_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'kormic'),
        'USER': os.environ.get('POSTGRES_USER', 'kormic'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'kormic'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
      
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        'CONN_HEALTH_CHECKS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Served by whitenoise (see MIDDLEWARE) directly from the app process --
# no separate nginx/CDN needed for the admin site's CSS/JS to work in
# production. `manage.py collectstatic` runs on every container start (see
# docker-compose.yml's `web` command), so this is a no-op if nothing changed.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "uploads"

# Korgut Django REST API settings
# CORS_ALLOW_ALL_ORIGINS is only ever safe for local development. Production
# (DEBUG=False) must supply an explicit comma-separated allow-list of
# frontend origins via DJANGO_CORS_ALLOWED_ORIGINS -- see
# deployment_checklist_to_do.md. Unset in production fails closed (no
# origins allowed) rather than silently staying wide open.
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        o.strip()
        for o in os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS", "").split(",")
        if o.strip()
    ]

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "accounts.permissions.IsTOTPEnrolled",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "auth": "60/min",
        "password_reset": "10/min",
        # claim/start and claim/verify are public by design (the OTP is
        # the auth), so both get an independent per-IP and per-email budget.
        # verify has no outbound email, so it can afford a looser IP rate.
        "claim_start_ip": "10/min",
        "claim_start_email": "3/min",
        "claim_verify_ip": "20/min",
        "claim_verify_email": "10/min",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# Redis-backed, shared across every gunicorn worker process (unlike
# LocMemCache, which is per-process and in-memory). This is load-bearing,
# not just a performance nicety: DRF's ScopedRateThrottle rate limits (auth,
# password_reset, claim_start/verify -- see DEFAULT_THROTTLE_RATES above)
# and the TOTP replay/lockout cache (accounts/totp.py) both assume one
# shared counter. With LocMemCache and >1 worker, each worker tracks its own
# count, so the real effective rate limit becomes configured_rate ×
# worker_count -- silently weaker than configured. Uses a separate Redis DB
# index from the Celery broker/result-backend (0/1) to keep keyspaces apart.
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("DJANGO_CACHE_URL", "redis://localhost:6379/2"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


# Celery -- background delivery for push notifications (see notifications/).
# Chat/agent processing itself stays synchronous (pure_multi_agent.runtime
# keeps its LangGraph checkpointer in-process, keyed by worker; routing that
# through Celery would split a student's conversation across worker
# processes). Celery is used only for the "send this push" side-effect,
# which is safely fire-and-forget.

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/1")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
# Global defaults, sized for quick tasks (push notifications). Anything that
# legitimately runs longer (url_discovery's crawl, notifications' proactive
# check-in batches) sets its own explicit soft_time_limit/time_limit on the
# @shared_task decorator -- see url_discovery/tasks.py and
# notifications/tasks.py. SOFT_TIME_LIMIT raises a catchable
# SoftTimeLimitExceeded 5s before the hard SIGKILL, so any future task that
# forgets to override still gets one chance to log/clean up instead of
# vanishing silently mid-loop.
CELERY_TASK_TIME_LIMIT = 30
CELERY_TASK_SOFT_TIME_LIMIT = 25
CELERY_TASK_ALWAYS_EAGER = os.environ.get("CELERY_TASK_ALWAYS_EAGER", "false").lower() == "true"

# Proactive agent outreach (notifications.tasks.run_proactive_checkins_task):
# once a day, the agent scans for students it hasn't nudged in
# PROACTIVE_CHECKIN_COOLDOWN_DAYS and, if their profile has a genuine gap
# worth mentioning, messages them on its own. Requires a `celery beat`
# process running alongside the worker -- see notifications/proactive.py.
PROACTIVE_CHECKIN_HOUR = int(os.environ.get("PROACTIVE_CHECKIN_HOUR", "9"))
PROACTIVE_CHECKIN_COOLDOWN_DAYS = int(os.environ.get("PROACTIVE_CHECKIN_COOLDOWN_DAYS", "7"))
# Students per fanned-out Celery sub-task (see run_proactive_checkins_task in
# notifications/tasks.py) -- keeps each sub-task's synchronous DB loop well
# under its own time limit and lets pushes for the whole batch go out as ~1
# Expo call instead of 1-per-student.
PROACTIVE_CHECKIN_BATCH_SIZE = int(os.environ.get("PROACTIVE_CHECKIN_BATCH_SIZE", "50"))

CELERY_BEAT_SCHEDULE = {
    "proactive-agent-checkins": {
        "task": "notifications.tasks.run_proactive_checkins_task",
        "schedule": crontab(hour=PROACTIVE_CHECKIN_HOUR, minute=0),
    },
}

# Expo push notifications (student mobile app).
EXPO_PUSH_ACCESS_TOKEN = os.environ.get("EXPO_PUSH_ACCESS_TOKEN", "")

# Email configuration -- used to deliver password-reset OTP codes (see
# accounts.email) and, in DEBUG, defaults to Ethereal's fake SMTP catch-all
# so nothing is ever really delivered from a dev machine. Production must
# set real EMAIL_HOST_USER/EMAIL_HOST_PASSWORD/DEFAULT_FROM_EMAIL (and
# EMAIL_HOST/EMAIL_PORT if not using Gmail-style TLS SMTP) via the
# environment -- see .env.template.
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.ethereal.email")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() == "true"
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "test@example.com")
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ["EMAIL_HOST"]
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() == "true"
    EMAIL_HOST_USER = os.environ["EMAIL_HOST_USER"]
    EMAIL_HOST_PASSWORD = os.environ["EMAIL_HOST_PASSWORD"]
    DEFAULT_FROM_EMAIL = os.environ["DEFAULT_FROM_EMAIL"]

# Frontend page the claim-invite email links to, e.g. "https://app.kormic.com/claim"
# (the student lands there with ?token=... and the page calls /api/claim/start/).
# No sane default exists -- it's a frontend URL we don't own -- so
# institutes_list.views.send_invites fails loudly if this is unset rather
# than emailing a broken link, same intentional-fail-loud pattern as the
# EMAIL_BACKEND requirement above.
CLAIM_PAGE_URL = os.getenv("CLAIM_PAGE_URL", "")


# Logging -- without this, Django/Celery's default logging goes essentially
# nowhere useful in production. Everything goes to stdout/stderr (the
# standard practice for containers: `docker logs`, and whatever log driver
# / CloudWatch agent the host has configured picks it up from there) rather
# than a file path this app would have to manage permissions/rotation for.
# DJANGO_LOG_LEVEL defaults to INFO so a bare production deploy gets useful
# output immediately; tighten with an env var if it's too chatty.
LOG_LEVEL = os.environ.get("DJANGO_LOG_LEVEL", "INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {

        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
