# Generated by Django 4.2.30 on 2026-08-27 08:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('knowledge_source', models.CharField(blank=True, default='', max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentIdentity',
            fields=[
                ('agent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('student', 'Student'), ('university', 'University')], db_index=True, max_length=20)),
                ('owner_id', models.CharField(db_index=True, max_length=255)),
                ('agent_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AriaMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('important_points', models.JSONField(blank=True, default=list)),
                ('universities_discussed', models.JSONField(blank=True, default=list)),
                ('github_profiles_analyzed', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('agent', 'Agent'), ('university', 'University'), ('presenter', 'Presenter'), ('intake', 'Intake')], db_index=True, max_length=20)),
                ('student_id', models.CharField(db_index=True, max_length=255)),
                ('university_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('student_id', models.CharField(max_length=255)),
                ('step', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(db_index=True, max_length=255)),
                ('university_name', models.CharField(blank=True, default='', max_length=255)),
                ('agent_name', models.CharField(blank=True, default='', max_length=255)),
                ('student_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('student_name', models.CharField(blank=True, default='', max_length=255)),
                ('program', models.CharField(blank=True, default='', max_length=255)),
                ('routed_to_name', models.CharField(blank=True, default='', max_length=255)),
                ('routed_to_email', models.CharField(blank=True, default='', max_length=255)),
                ('question', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('urgency_reason', models.TextField(blank=True, default='')),
                ('escalation_chain', models.JSONField(blank=True, default=list)),
                ('answer', models.TextField(blank=True, default='')),
                ('answered_by', models.CharField(blank=True, default='', max_length=255)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='universities.knowledgegroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresenterAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('event', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, default='')),
                ('details', models.TextField(blank=True, default='')),
                ('profile_name', models.CharField(blank=True, default='', max_length=255)),
                ('question', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('agent_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('institution', models.CharField(blank=True, default='', max_length=500)),
                ('major', models.CharField(blank=True, default='', max_length=255)),
                ('program', models.CharField(blank=True, default='', max_length=255)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('gpa_scale', models.CharField(blank=True, default='', max_length=50)),
                ('gpa_text', models.CharField(blank=True, default='', max_length=100)),
                ('gre_quant', models.FloatField(blank=True, null=True)),
                ('gre_verbal', models.FloatField(blank=True, null=True)),
                ('toefl', models.FloatField(blank=True, null=True)),
                ('ielts', models.FloatField(blank=True, null=True)),
                ('english_score_text', models.CharField(blank=True, default='', max_length=100)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('budget_text', models.CharField(blank=True, default='', max_length=100)),
                ('work_months', models.FloatField(blank=True, default=0, null=True)),
                ('github', models.CharField(blank=True, default='', max_length=500)),
                ('github_assessment', models.JSONField(blank=True, default=dict)),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=500)),
                ('linkedin_profile', models.JSONField(blank=True, default=dict)),
                ('profile_image_path', models.CharField(blank=True, default='', max_length=1000)),
                ('notes', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='api', max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('technical_skills', models.JSONField(blank=True, default=list)),
                ('soft_skills', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('research', models.TextField(blank=True, default='')),
                ('research_interests', models.JSONField(blank=True, default=list)),
                ('publications', models.JSONField(blank=True, default=list)),
                ('publications_count', models.IntegerField(blank=True, null=True)),
                ('career_goals', models.JSONField(blank=True, default=list)),
                ('conversation_insights', models.JSONField(blank=True, default=list)),
                ('assessments', models.JSONField(blank=True, default=dict)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('academic_intelligence', models.JSONField(blank=True, default=dict)),
                ('technical_intelligence', models.JSONField(blank=True, default=dict)),
                ('research_intelligence', models.JSONField(blank=True, default=dict)),
                ('behaviour_intelligence', models.JSONField(blank=True, default=dict)),
                ('overall_profile_score', models.IntegerField(blank=True, default=0)),
                ('overall_profile', models.JSONField(blank=True, default=dict)),
                ('profile_completeness', models.JSONField(blank=True, default=dict)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('roadmap', models.JSONField(blank=True, default=dict)),
                ('disciplines', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('parser_status', models.CharField(blank=True, default='', max_length=100)),
                ('parser_engine', models.CharField(blank=True, default='', max_length=100)),
                ('response_mode', models.CharField(blank=True, default='', max_length=100)),
                ('work_experience_summary', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityQuestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(db_index=True, max_length=255)),
                ('student_name', models.CharField(blank=True, default='', max_length=255)),
                ('question', models.TextField()),
                ('topic', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(db_index=True, max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('answered_by', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_answers', to='django_api.pendingquery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityKnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(db_index=True, max_length=255)),
                ('topic', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('source_type', models.CharField(default='unknown', max_length=50)),
                ('source_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('times_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to='universities.knowledgegroup')),
            ],
            options={
                'ordering': ['-confidence', '-times_used'],
            },
        ),
        migrations.CreateModel(
            name='UniversityInterestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(choices=[('searched', 'Searched'), ('fit_check', 'Fit Check')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_interest_events', to='django_api.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_message', models.TextField(blank=True, default='')),
                ('roadmap', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_versions', to='django_api.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('original_filename', models.CharField(max_length=500)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_uploads', to='django_api.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkedInAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_paths', models.JSONField(blank=True, default=list)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_analyses', to='django_api.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.CharField(max_length=500)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_analyses', to='django_api.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FitAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(db_index=True, max_length=255)),
                ('assessment', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_assessments', to='django_api.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('original_filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(blank=True, default='', max_length=150)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='django_api.chatmessage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='agentidentity',
            constraint=models.UniqueConstraint(fields=('owner_type', 'owner_id'), name='uq_agent_identity_owner'),
        ),
        migrations.AddField(
            model_name='agentconversationlog',
            name='asker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_conversations', to='django_api.agentidentity'),
        ),
        migrations.AddField(
            model_name='agentconversationlog',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_conversations', to='django_api.agentidentity'),
        ),
        migrations.AddIndex(
            model_name='universityinterestevent',
            index=models.Index(fields=['university_id', 'student'], name='django_api__univers_7304da_idx'),
        ),
        migrations.AddConstraint(
            model_name='universityinterestevent',
            constraint=models.UniqueConstraint(fields=('student', 'university_id', 'source'), name='unique_university_interest_event_per_source'),
        ),
    ]
