# Generated by Django 5.2.16 on 2026-07-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('student_id', models.CharField(max_length=255)),
                ('step', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('institution', models.CharField(blank=True, default='', max_length=500)),
                ('major', models.CharField(blank=True, default='', max_length=255)),
                ('program', models.CharField(blank=True, default='', max_length=255)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('gpa_scale', models.CharField(blank=True, default='', max_length=50)),
                ('gpa_text', models.CharField(blank=True, default='', max_length=100)),
                ('gre_quant', models.FloatField(blank=True, null=True)),
                ('gre_verbal', models.FloatField(blank=True, null=True)),
                ('toefl', models.FloatField(blank=True, null=True)),
                ('ielts', models.FloatField(blank=True, null=True)),
                ('english_score_text', models.CharField(blank=True, default='', max_length=100)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('budget_text', models.CharField(blank=True, default='', max_length=100)),
                ('work_months', models.FloatField(blank=True, default=0, null=True)),
                ('github', models.CharField(blank=True, default='', max_length=500)),
                ('github_assessment', models.JSONField(blank=True, default=dict)),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=500)),
                ('linkedin_profile', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='api', max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('technical_skills', models.JSONField(blank=True, default=list)),
                ('soft_skills', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('research', models.TextField(blank=True, default='')),
                ('research_interests', models.JSONField(blank=True, default=list)),
                ('publications', models.JSONField(blank=True, default=list)),
                ('publications_count', models.IntegerField(blank=True, null=True)),
                ('career_goals', models.JSONField(blank=True, default=list)),
                ('conversation_insights', models.JSONField(blank=True, default=list)),
                ('assessments', models.JSONField(blank=True, default=dict)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('academic_intelligence', models.JSONField(blank=True, default=dict)),
                ('technical_intelligence', models.JSONField(blank=True, default=dict)),
                ('research_intelligence', models.JSONField(blank=True, default=dict)),
                ('behaviour_intelligence', models.JSONField(blank=True, default=dict)),
                ('overall_profile_score', models.IntegerField(blank=True, default=0)),
                ('overall_profile', models.JSONField(blank=True, default=dict)),
                ('profile_completeness', models.JSONField(blank=True, default=dict)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('roadmap', models.JSONField(blank=True, default=dict)),
                ('disciplines', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('parser_status', models.CharField(blank=True, default='', max_length=100)),
                ('parser_engine', models.CharField(blank=True, default='', max_length=100)),
                ('response_mode', models.CharField(blank=True, default='', max_length=100)),
                ('work_experience_summary', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
