# Generated by Django 5.2.16 on 2026-07-13 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0002_chatmessage_fitassessment_githubanalysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AriaMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('important_points', models.JSONField(blank=True, default=list)),
                ('universities_discussed', models.JSONField(blank=True, default=list)),
                ('github_profiles_analyzed', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(db_index=True, max_length=255)),
                ('university_name', models.CharField(blank=True, default='', max_length=255)),
                ('agent_name', models.CharField(blank=True, default='', max_length=255)),
                ('student_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('student_name', models.CharField(blank=True, default='', max_length=255)),
                ('program', models.CharField(blank=True, default='', max_length=255)),
                ('question', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('urgency_reason', models.TextField(blank=True, default='')),
                ('escalation_chain', models.JSONField(blank=True, default=list)),
                ('answer', models.TextField(blank=True, default='')),
                ('answered_by', models.CharField(blank=True, default='', max_length=255)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresenterAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('event', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, default='')),
                ('details', models.TextField(blank=True, default='')),
                ('profile_name', models.CharField(blank=True, default='', max_length=255)),
                ('question', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityKnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(db_index=True, max_length=255)),
                ('topic', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('source_type', models.CharField(default='unknown', max_length=50)),
                ('source_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('times_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-confidence', '-times_used'],
            },
        ),
        migrations.CreateModel(
            name='UniversityQuestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(db_index=True, max_length=255)),
                ('student_name', models.CharField(blank=True, default='', max_length=255)),
                ('question', models.TextField()),
                ('topic', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(db_index=True, max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('answered_by', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_answers', to='django_api.pendingquery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
