# Generated by Django 5.2.16 on 2026-07-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0003_ariamemory_pendingquery_presenterauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image_path',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
