# Generated by Django 5.2.16 on 2026-07-16 11:57

from django.db import migrations, models


def rename_aria_channel_to_agent(apps, schema_editor):
    ChatMessage = apps.get_model("django_api", "ChatMessage")
    ChatMessage.objects.filter(channel="aria").update(channel="agent")


def rename_agent_channel_to_aria(apps, schema_editor):
    ChatMessage = apps.get_model("django_api", "ChatMessage")
    ChatMessage.objects.filter(channel="agent").update(channel="aria")


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0004_studentprofile_profile_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='agent_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='channel',
            field=models.CharField(choices=[('agent', 'Agent'), ('university', 'University'), ('presenter', 'Presenter'), ('intake', 'Intake')], db_index=True, max_length=20),
        ),
        migrations.RunPython(rename_aria_channel_to_agent, rename_agent_channel_to_aria),
    ]
