# Generated by Django 5.2.16 on 2026-07-23 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0005_agent_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityInterestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(choices=[('searched', 'Searched'), ('fit_check', 'Fit Check')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_interest_events', to='django_api.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['university_id', 'student'], name='django_api__univers_7304da_idx')],
            },
        ),
    ]
