# Generated by Django 5.2.16 on 2026-07-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0008_dedupe_university_interest_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingquery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', max_length=20),
        ),
    ]
