# Generated by Django 4.2.30 on 2026-08-10 11:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_knowledgegroup_and_more'),
        ('django_api', '0010_chatmessage_edited_at_chatattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('knowledge_source', models.CharField(blank=True, default='', max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentIdentity',
            fields=[
                ('agent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('student', 'Student'), ('university', 'University')], db_index=True, max_length=20)),
                ('owner_id', models.CharField(db_index=True, max_length=255)),
                ('agent_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pendingquery',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='universities.knowledgegroup'),
        ),
        migrations.AddField(
            model_name='pendingquery',
            name='routed_to_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pendingquery',
            name='routed_to_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='universityknowledgeentry',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to='universities.knowledgegroup'),
        ),
        migrations.AddConstraint(
            model_name='agentidentity',
            constraint=models.UniqueConstraint(fields=('owner_type', 'owner_id'), name='uq_agent_identity_owner'),
        ),
        migrations.AddField(
            model_name='agentconversationlog',
            name='asker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_conversations', to='django_api.agentidentity'),
        ),
        migrations.AddField(
            model_name='agentconversationlog',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_conversations', to='django_api.agentidentity'),
        ),
    ]
