# Generated by Django 4.2.30 on 2026-08-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0011_agentconversationlog_agentidentity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingquery',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
