# Generated by Django 6.0.7 on 2026-07-10 21:59

import django.db.models.deletion
import identity_verification.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBiometricPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('skipped', 'Skipped'), ('unavailable', 'Unavailable')], max_length=20)),
                ('platform', models.CharField(max_length=20)),
                ('app_version', models.CharField(max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_biometric_preference', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityVerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_nonce', models.CharField(default=identity_verification.models.generate_session_nonce, editable=False, max_length=128)),
                ('challenge_sequence', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('expired', 'Expired')], db_index=True, default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('previous_head', models.CharField(blank=True, default='', max_length=128)),
                ('current_head', models.CharField(blank=True, default='', max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_sessions', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentityVerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_payload', models.JSONField()),
                ('detector_provider', models.CharField(max_length=120)),
                ('platform', models.CharField(max_length=20)),
                ('app_version', models.CharField(max_length=80)),
                ('final_liveness_result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=20)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=120)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='identity_verification.identityverificationsession')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentityVerificationProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(db_index=True, max_length=255)),
                ('verification_record_hash', models.CharField(db_index=True, max_length=128)),
                ('current_head', models.CharField(db_index=True, max_length=128)),
                ('freshness_timestamp', models.DateTimeField()),
                ('challenge', models.CharField(max_length=255)),
                ('signing_epoch', models.PositiveIntegerField()),
                ('signature', models.TextField()),
                ('authority_identifier', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='identity_verification.identityverificationresult')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='identity_verification.identityverificationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='identityverificationsession',
            index=models.Index(fields=['account', 'status'], name='identity_ve_account_71d739_idx'),
        ),
    ]
