# Generated by Django 5.2.16 on 2026-07-28 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('totp_removed', 'TOTP removed'), ('password_reset', 'Password reset'), ('sessions_revoked', 'Sessions revoked'), ('registered', 'Registered'), ('login_succeeded', 'Login succeeded'), ('login_failed', 'Login failed'), ('logged_out', 'Logged out')], max_length=20)),
                ('target_email', models.CharField(blank=True, default='', max_length=255)),
                ('target_role', models.CharField(blank=True, default='', max_length=20)),
                ('target_student_id', models.CharField(blank=True, default='', max_length=255)),
                ('target_university_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_log_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
