# Generated by Django 5.2.16 on 2026-07-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_superuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('totp_removed', 'TOTP removed'), ('password_reset', 'Password reset'), ('sessions_revoked', 'Sessions revoked'), ('registered', 'Registered'), ('login_succeeded', 'Login succeeded'), ('login_failed', 'Login failed'), ('logged_out', 'Logged out'), ('password_reset_requested', 'Password reset requested')], max_length=32),
        ),
    ]
