# Generated by Django 4.2.30 on 2026-08-27 08:38

from django.db import migrations, models
import django.db.models.deletion
import institutes_list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityStudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_verification', models.CharField(blank=True, default='', max_length=500)),
                ('format_version', models.CharField(default='v1', max_length=20)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('source_file_path', models.CharField(blank=True, default='', max_length=1000)),
                ('source_file_name', models.CharField(blank=True, default='', max_length=500)),
                ('source_file_content_type', models.CharField(blank=True, default='', max_length=150)),
                ('source_file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_lists', to='institutes.institute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.CharField(db_index=True, max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=255)),
                ('degree_level', models.CharField(blank=True, default='', max_length=100)),
                ('expected_graduation', models.CharField(blank=True, default='', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('year_in_college', models.CharField(blank=True, default='', max_length=20)),
                ('program_name', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='unclaimed', max_length=20)),
                ('claim_token', models.CharField(default=institutes_list.models._new_claim_token, max_length=64, unique=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('otp_hash', models.CharField(blank=True, default='', max_length=128)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_student_id', models.CharField(blank=True, default='', max_length=255)),
                ('divergences', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='institutes_list.universitystudentlist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='listedstudent',
            constraint=models.UniqueConstraint(fields=('source_list', 'email'), name='uniq_email_per_list'),
        ),
    ]
