# Generated by Django 4.2.30 on 2026-08-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedstudent',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
