# Generated by Django 4.2.30 on 2026-08-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes_list', '0002_listedstudent_invited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitystudentlist',
            name='source_file_content_type',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='universitystudentlist',
            name='source_file_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='universitystudentlist',
            name='source_file_path',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='universitystudentlist',
            name='source_file_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
