# Generated by Django 5.2.16 on 2026-07-14 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubOAuthConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.BigIntegerField()),
                ('github_username', models.CharField(max_length=255)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, default='', max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_oauth_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
