# Generated by Django 5.2.16 on 2026-07-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_githuboauthconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='githuboauthconnection',
            name='github_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='githuboauthconnection',
            name='github_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
