# Generated by Django 5.2.16 on 2026-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_githuboauthconnection_github_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('university', 'University'), ('superuser', 'Superuser')], max_length=20),
        ),
    ]
