# Generated by Django 4.2.30 on 2026-08-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='institute_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('university', 'University'), ('institute', 'Institute'), ('superuser', 'Superuser')], max_length=20),
        ),
    ]
