# Generated by Django 4.2.30 on 2026-08-27 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.TextField()),
                ('root_domain', models.CharField(blank=True, default='', max_length=255)),
                ('allowed_domains', models.JSONField(blank=True, default=list)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('stop_requested', 'Stop requested'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=40)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('top_n', models.IntegerField(default=20)),
                ('auto_apply', models.BooleanField(default=True)),
                ('scrape_result', models.JSONField(blank=True, default=dict)),
                ('pages_discovered', models.IntegerField(default=0)),
                ('pages_crawled', models.IntegerField(default=0)),
                ('relevant_count', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('excluded_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('current_url', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_jobs', to='universities.university')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryClusterApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('url_count', models.IntegerField(default=0)),
                ('urls', models.JSONField(blank=True, default=list)),
                ('approved_by', models.CharField(blank=True, default='', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_approvals', to='url_discovery.discoveryjob')),
                ('knowledge_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_cluster_approvals', to='universities.knowledgegroup')),
            ],
            options={
                'ordering': ['-approved_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.TextField()),
                ('normalized_url', models.TextField()),
                ('final_url', models.TextField(blank=True, null=True)),
                ('parent_url', models.TextField(blank=True, null=True)),
                ('anchor_text', models.CharField(blank=True, max_length=500, null=True)),
                ('page_title', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('h1', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=32, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('crawl_depth', models.IntegerField(default=0)),
                ('primary_category', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_categories_json', models.TextField(default='[]')),
                ('category_scores_json', models.TextField(default='{}')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('decision_status', models.CharField(db_index=True, default='pending', max_length=40)),
                ('is_discovery_only', models.BooleanField(default=True)),
                ('classification_reason', models.TextField(blank=True, null=True)),
                ('exclusion_reason', models.TextField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('crawled_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='url_discovery.discoveryjob')),
            ],
        ),
        migrations.AddConstraint(
            model_name='discoveryclusterapproval',
            constraint=models.UniqueConstraint(fields=('job', 'category'), name='uq_discovery_cluster_job_category'),
        ),
        migrations.AddIndex(
            model_name='discoveredurl',
            index=models.Index(fields=['job', 'decision_status'], name='ix_durl_job_status'),
        ),
        migrations.AddIndex(
            model_name='discoveredurl',
            index=models.Index(fields=['job', 'primary_category'], name='ix_durl_job_category'),
        ),
        migrations.AddConstraint(
            model_name='discoveredurl',
            constraint=models.UniqueConstraint(fields=('job', 'normalized_url'), name='uq_discovery_job_normalized_url'),
        ),
    ]
