# Generated by Django 4.2.30 on 2026-08-12 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_knowledgegroup_and_more'),
        ('url_discovery', '0002_discoveryjob_auto_apply_discoveryjob_scrape_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryClusterApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('url_count', models.IntegerField(default=0)),
                ('urls', models.JSONField(blank=True, default=list)),
                ('approved_by', models.CharField(blank=True, default='', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_approvals', to='url_discovery.discoveryjob')),
                ('knowledge_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_cluster_approvals', to='universities.knowledgegroup')),
            ],
            options={
                'ordering': ['-approved_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='discoveryclusterapproval',
            constraint=models.UniqueConstraint(fields=('job', 'category'), name='uq_discovery_cluster_job_category'),
        ),
    ]
