# Generated by Django 5.2.16 on 2026-07-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('agent_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('tagline', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('contact_email', models.CharField(blank=True, default='', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('website_url', models.CharField(blank=True, default='', max_length=1000)),
                ('admissions_office_address', models.TextField(blank=True, default='')),
                ('eligibility_criteria', models.JSONField(blank=True, default=list)),
                ('scrape_urls', models.JSONField(blank=True, default=list)),
                ('tone_descriptors', models.JSONField(blank=True, default=list)),
                ('best_fit_notes', models.TextField(blank=True, default='')),
                ('not_best_fit_notes', models.TextField(blank=True, default='')),
                ('communication_style_notes', models.TextField(blank=True, default='')),
                ('never_do_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
