# Generated by Django 4.2.30 on 2026-08-27 08:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import universities.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('agent_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('tagline', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('contact_email', models.CharField(blank=True, default='', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('website_url', models.CharField(blank=True, default='', max_length=1000)),
                ('admissions_office_address', models.TextField(blank=True, default='')),
                ('eligibility_criteria', models.JSONField(blank=True, default=list)),
                ('scrape_urls', models.JSONField(blank=True, default=list)),
                ('min_fit_score_threshold', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('priority_tier_bounds', models.JSONField(blank=True, default=universities.models.default_priority_tier_bounds)),
                ('tone_descriptors', models.JSONField(blank=True, default=list)),
                ('best_fit_notes', models.TextField(blank=True, default='')),
                ('not_best_fit_notes', models.TextField(blank=True, default='')),
                ('communication_style_notes', models.TextField(blank=True, default='')),
                ('never_do_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, default='', max_length=1000)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_jobs', to='universities.university')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('admissions', 'Admissions'), ('international', 'International Office'), ('money', 'Money'), ('campus_life', 'Campus Life')], max_length=30)),
                ('escalation_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('escalation_contact_email', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_groups', to='universities.university')),
            ],
            options={
                'ordering': ['university_id', 'slug'],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgegroup',
            constraint=models.UniqueConstraint(fields=('university', 'slug'), name='uq_knowledge_group_university_slug'),
        ),
    ]
