# Generated by Django 5.2.16 on 2026-07-23 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_seed_legacy_universities'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='min_fit_score_threshold',
            field=models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
