# Generated by Django 5.2.16 on 2026-07-24 07:02

import universities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_min_fit_score_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='priority_tier_bounds',
            field=models.JSONField(blank=True, default=universities.models.default_priority_tier_bounds),
        ),
    ]
