# Generated by Django 4.2.30 on 2026-08-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_university_priority_tier_bounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('admissions', 'Admissions'), ('international', 'International Office'), ('money', 'Money'), ('campus_life', 'Campus Life')], max_length=30)),
                ('escalation_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('escalation_contact_email', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_groups', to='universities.university')),
            ],
            options={
                'ordering': ['university_id', 'slug'],
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgegroup',
            constraint=models.UniqueConstraint(fields=('university', 'slug'), name='uq_knowledge_group_university_slug'),
        ),
    ]
