# Generated by Django 5.2.16 on 2026-07-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('agent_reply', 'Agent Reply'), ('pending_query_resolved', 'Pending Query Resolved'), ('agent_initiated', 'Agent Initiated'), ('proactive_checkin', 'Proactive Check-in'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
